## Numpy Exercises

1. Import np

In [13]:
import numpy as np

2. Create an array of 10 zeros

In [17]:
arr1 = np.zeros(10, dtype=np.int8)
print(arr1)

[0 0 0 0 0 0 0 0 0 0]


3. Create an array of 10 ones

In [18]:
arr2 = np.ones(10, dtype=np.int8)
print(arr2)

[1 1 1 1 1 1 1 1 1 1]


4. Create an array of 10 fives

In [19]:
arr3 = np.ones(10, dtype=np.int8) * 5
print(arr3)

[5 5 5 5 5 5 5 5 5 5]


5. Create an array of integers from 10 to 50

In [20]:
arr4 = np.arange(10, 51)
print(arr4)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


6. Create an array of even integers from 10 to 50

In [21]:
arr5 = np.arange(10, 51, 2)
print(arr5)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


7. Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
arr6 = np.arange(9).reshape(3, 3)
print(arr6)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


8. Create a 3x3 identity matrix

In [23]:
arr7 = np.eye(3)
print(arr7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


9. Use NumPy to generate a random number between 0 and 1

In [24]:
arr8 = np.random.rand(1)
print(arr8)

[0.40162513]
